version: 2

sources:
  - name: raw
    description: "Raw schema from the PostgreSQL database containing scraped data."
    schema: raw
    tables:
      - name: messages
        description: "Raw Telegram messages as JSON blobs."

  - name: raw_enrichment # New source for enrichment data
    description: "Schema containing raw results from enrichment processes like YOLO."
    schema: raw_enrichment
    tables:
      - name: image_detections
        description: "Raw object detection results from YOLOv8."
